FROM jenkins/jenkins:lts

USER 0

COPY executors.groovy /usr/share/jenkins/ref/init.groovy.d/executors.groovy

# RUN apt update
RUN apt update 
RUN apt install -qyy curl wget git

# install nodejs
RUN curl -SLO https://deb.nodesource.com/nsolid_setup_deb.sh
RUN chmod 500 nsolid_setup_deb.sh
RUN ./nsolid_setup_deb.sh 20
RUN apt-get install nodejs -y

USER 1000
